apiVersion: v1
kind: Namespace
metadata:
  annotations:
    app.openshift.io/vcs-uri: https://github.com/ibm-cloud-architecture/eda-kc-gitops.git?ref=HEAD
  creationTimestamp: null
  name: kc-cicd
spec: {}
status: {}
