apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  creationTimestamp: null
  name: ci-dryrun-from-push-template
  namespace: kc-cicd
spec:
  params:
  - default: master
    description: The git revision
    name: io.openshift.build.commit.ref
  - description: The specific commit SHA
    name: io.openshift.build.commit.id
  - description: The git repository url
    name: gitrepositoryurl
  - description: The repository name for this PullRequest
    name: fullname
  resourcetemplates:
  - apiVersion: tekton.dev/v1beta1
    kind: PipelineRun
    metadata:
      creationTimestamp: null
      name: ci-dryrun-from-push-$(uid)
    spec:
      params:
      - name: REPO
        value: $(tt.params.fullname)
      - name: GIT_REPO
        value: $(tt.params.gitrepositoryurl)
      - name: COMMIT_SHA
        value: $(tt.params.io.openshift.build.commit.id)
      pipelineRef:
        name: ci-dryrun-from-push-pipeline
      resources:
      - name: source-repo
        resourceSpec:
          params:
          - name: revision
            value: $(tt.params.io.openshift.build.commit.id)
          - name: url
            value: $(tt.params.gitrepositoryurl)
          type: git
      serviceAccountName: pipeline
    status: {}
status: {}
